services:
  web:
    container_name: ror-web
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0

  postgres:
    container_name: ror-db
    image: postgres:13
    environment:
      - POSTGRES_DB=ror
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
