services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - DB_NAME=ror
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
